services:
  - type: web
    name: fms-nyala-demo
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn fms_nyala.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com